import { Item, Item_v2 } from './item-interface';

const images = [
  'demo-img (1).jpg',
  'demo-img (2).jpg',
  'demo-img (3).jpg',
  'demo-img (4).jpg',
  'demo-img (5).jpg',
  'demo-img (6).jpg',
  'demo-img (7).jpg',
  'demo-img (8).jpg',
  'demo-img (9).jpg',
  'demo-img (10).jpg',
  'demo-img (11).jpg',
  'demo-img (12).jpg',
  'demo-img (13).jpg',
  'demo-img (14).jpg',
  'demo-img (15).jpg',
  'demo-img (16).jpg',
  'demo-img (17).jpg',
  'demo-img (18).jpg',
  'demo-img (19).jpg',
  'demo-img (20).jpg',
  'demo-img (21).jpg',
];

const getRandomImages = (
  imageArray: string[],
  count: number
): Array<{ id: number; value: string }> => {
  const shuffled = imageArray.sort(() => 0.5 - Math.random());
  return shuffled
    .slice(0, count)
    .map((value, index) => ({ id: index + 1, value }));
};

export const ITEMS: Item[] = [
  {
    id: 1,
    name: 'T-Shirt Basic',
    price: 25,
    pricesale: 20,
    type: 'Clothing',
    des: 'A basic t-shirt made from 100% cotton.',
    origin: 'Vietnam',
    quantity: 50,
    size: [
      { id: 1, value: 'S' },
      { id: 2, value: 'M' },
      { id: 3, value: 'L' },
      { id: 4, value: 'XL' },
      { id: 5, value: 'Over Size' },
    ],
    color: [
      { id: 1, value: 'Black' },
      { id: 2, value: 'White' },
      { id: 3, value: 'Gray' },
    ],
    brand: 'LUONVUITUOI',
    image: getRandomImages(images, 5),
  },
  {
    id: 2,
    name: 'Sneakers Sport',
    price: 70,
    pricesale: 60,
    type: 'Footwear',
    des: 'Comfortable sneakers for everyday use.',
    origin: 'China',
    quantity: 30,
    size: [
      { id: 1, value: 'S' },
      { id: 2, value: 'M' },
      { id: 3, value: 'L' },
      { id: 4, value: 'XL' },
      { id: 5, value: 'Over Size' },
    ],
    color: [
      { id: 1, value: 'Red' },
      { id: 2, value: 'Blue' },
      { id: 3, value: 'Green' },
    ],
    brand: 'LUONVUITUOI',
    image: getRandomImages(images, 5),
  },
  {
    id: 3,
    name: 'Laptop Backpack',
    price: 45,
    pricesale: 40,
    type: 'Bags',
    des: 'A stylish backpack for your laptop.',
    origin: 'Vietnam',
    quantity: 25,
    size: [
      { id: 1, value: 'S' },
      { id: 2, value: 'M' },
      { id: 3, value: 'L' },
      { id: 4, value: 'XL' },
      { id: 5, value: 'Over Size' },
    ],
    color: [
      { id: 1, value: 'Black' },
      { id: 2, value: 'Navy' },
    ],
    brand: 'LUONVUITUOI',
    image: getRandomImages(images, 5),
  },
  {
    id: 4,
    name: 'Wireless Headphones',
    price: 120,
    pricesale: 100,
    type: 'Electronics',
    des: 'Noise-cancelling wireless headphones.',
    origin: 'USA',
    quantity: 15,
    size: [
      { id: 1, value: 'S' },
      { id: 2, value: 'M' },
      { id: 3, value: 'L' },
      { id: 4, value: 'XL' },
      { id: 5, value: 'Over Size' },
    ],
    color: [
      { id: 1, value: 'Black' },
      { id: 2, value: 'White' },
    ],
    brand: 'LUONVUITUOI',
    image: getRandomImages(images, 5),
  },
  {
    id: 5,
    name: 'Wool Sweater',
    price: 50,
    pricesale: 45,
    type: 'Clothing',
    des: 'A warm wool sweater for cold days.',
    origin: 'Iceland',
    quantity: 20,
    size: [
      { id: 1, value: 'S' },
      { id: 2, value: 'M' },
      { id: 3, value: 'L' },
      { id: 4, value: 'XL' },
      { id: 5, value: 'Over Size' },
    ],
    color: [
      { id: 1, value: 'Beige' },
      { id: 2, value: 'Brown' },
    ],
    brand: 'GUCCHI',
    image: getRandomImages(images, 5),
  },
  {
    id: 6,
    name: 'Smartwatch',
    price: 250,
    pricesale: 230,
    type: 'Electronics',
    des: 'A smartwatch with various fitness features.',
    origin: 'USA',
    quantity: 10,
    size: [
      { id: 1, value: 'S' },
      { id: 2, value: 'M' },
      { id: 3, value: 'L' },
      { id: 4, value: 'XL' },
      { id: 5, value: 'Over Size' },
    ],
    color: [
      { id: 1, value: 'Black' },
      { id: 2, value: 'Silver' },
    ],
    brand: 'GUCCHI',
    image: getRandomImages(images, 5),
  },
  {
    id: 7,
    name: 'Formal Shoes',
    price: 90,
    pricesale: 80,
    type: 'Footwear',
    des: 'Elegant formal shoes for special occasions.',
    origin: 'Italy',
    quantity: 12,
    size: [
      { id: 1, value: 'S' },
      { id: 2, value: 'M' },
      { id: 3, value: 'L' },
      { id: 4, value: 'XL' },
      { id: 5, value: 'Over Size' },
    ],
    color: [
      { id: 1, value: 'Black' },
      { id: 2, value: 'Brown' },
    ],
    brand: 'GUCCHI',
    image: getRandomImages(images, 5),
  },
  {
    id: 8,
    name: 'Graphic T-Shirt',
    price: 30,
    pricesale: 25,
    type: 'Clothing',
    des: 'A stylish graphic t-shirt.',
    origin: 'Vietnam',
    quantity: 40,
    size: [
      { id: 1, value: 'S' },
      { id: 2, value: 'M' },
      { id: 3, value: 'L' },
      { id: 4, value: 'XL' },
      { id: 5, value: 'Over Size' },
    ],
    color: [
      { id: 1, value: 'White' },
      { id: 2, value: 'Black' },
    ],
    brand: 'VESPA',
    image: getRandomImages(images, 5),
  },
  {
    id: 9,
    name: 'Sports Watch',
    price: 70,
    pricesale: 60,
    type: 'Electronics',
    des: 'Durable watch for sports activities.',
    origin: 'Japan',
    quantity: 18,
    size: [
      { id: 1, value: 'S' },
      { id: 2, value: 'M' },
      { id: 3, value: 'L' },
      { id: 4, value: 'XL' },
      { id: 5, value: 'Over Size' },
    ],
    color: [
      { id: 1, value: 'Black' },
      { id: 2, value: 'Orange' },
    ],
    brand: 'VESPA',
    image: getRandomImages(images, 5),
  },
  {
    id: 10,
    name: 'Leather Jacket',
    price: 150,
    pricesale: 140,
    type: 'Clothing',
    des: 'Stylish leather jacket for men.',
    origin: 'USA',
    quantity: 8,
    size: [
      { id: 1, value: 'S' },
      { id: 2, value: 'M' },
      { id: 3, value: 'L' },
      { id: 4, value: 'XL' },
      { id: 5, value: 'Over Size' },
    ],
    color: [
      { id: 1, value: 'Black' },
      { id: 2, value: 'Brown' },
    ],
    brand: 'VESPA',
    image: getRandomImages(images, 5),
  },
  {
    id: 11,
    name: 'Leather Jacket GH35',
    price: 1000000,
    pricesale: 900000,
    type: 'Clothing',
    des: 'Stylish leather jacket for men.',
    origin: 'USA',
    quantity: 8,
    size: [
      { id: 1, value: 'S' },
      { id: 2, value: 'M' },
      { id: 3, value: 'L' },
      { id: 4, value: 'XL' },
      { id: 5, value: 'Over Size' },
    ],
    color: [
      { id: 1, value: 'Orange' },
      { id: 2, value: 'Pink' },
    ],
    brand: 'DIOR',
    image: getRandomImages(images, 5),
  },
  {
    id: 12,
    name: 'Leather Jacket KC43',
    price: 100000,
    pricesale: 400000,
    type: 'Clothing',
    des: 'Stylish leather jacket for men.',
    origin: 'USA',
    quantity: 8,
    size: [
      { id: 1, value: 'S' },
      { id: 2, value: 'M' },
      { id: 3, value: 'L' },
      { id: 4, value: 'XL' },
      { id: 5, value: 'Over Size' },
    ],
    color: [
      { id: 1, value: 'Green' },
      { id: 2, value: 'Gray' },
    ],
    brand: 'VERSACE',
    image: getRandomImages(images, 5),
  },
  {
    id: 13,
    name: 'Leather Jacket KC4366 ther Jacket KC4366 Leather Jacket KC4366 Leather Jacket KC4366',
    price: 100000,
    pricesale: 40000,
    type: 'Clothing',
    des: 'Stylish leather jacket for men.',
    origin: 'USA',
    quantity: 8,
    size: [
      { id: 1, value: 'S' },
      { id: 2, value: 'M' },
      { id: 3, value: 'L' },
      { id: 4, value: 'XL' },
      { id: 5, value: 'Over Size' },
    ],
    color: [
      { id: 1, value: 'Green' },
      { id: 2, value: 'Gray' },
    ],
    brand: 'MICHAEL KORS',
    image: getRandomImages(images, 5),
  },
];

/**Xu ly data item v2: start */
const dataItemAPI = {
  result: [
    {
      id: 7,
      cat_Id: 1,
      nat_Id: 1,
      bra_Id: 1,
      sup_Id: 1,
      name: 'Áo polo thể thao',
      status: true,
      productVariations: [
        {
          id: 9,
          pro_Id: 7,
          col_Id: 5,
          siz_Id: 1,
          price: 120000,
          importPrice: 110000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952084/TShirt/%C3%81o%20polo%20nam%20th%E1%BB%83%20thao/lp0dfu2gedcs42ajfmse.webp',
          quantity: 50,
          desc: 'Áo polo phù hợp cho những hoạt động thể thao ngoài trời.',
          discount: 0,
          status: true,
        },
        {
          id: 10,
          pro_Id: 7,
          col_Id: 3,
          siz_Id: 1,
          price: 120000,
          importPrice: 110000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952083/TShirt/%C3%81o%20polo%20nam%20th%E1%BB%83%20thao/thjvmvtpfdj9ifqqvhnc.webp',
          quantity: 80,
          desc: 'string',
          discount: 0,
          status: true,
        },
        {
          id: 11,
          pro_Id: 7,
          col_Id: 2,
          siz_Id: 3,
          price: 120000,
          importPrice: 110000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952083/TShirt/%C3%81o%20polo%20nam%20th%E1%BB%83%20thao/zb6rcw9dtc4zpoobuyrz.webp',
          quantity: 50,
          desc: 'string',
          discount: 0,
          status: true,
        },
        {
          id: 12,
          pro_Id: 7,
          col_Id: 3,
          siz_Id: 2,
          price: 130000,
          importPrice: 120000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952083/TShirt/%C3%81o%20polo%20nam%20th%E1%BB%83%20thao/zb6rcw9dtc4zpoobuyrz.webp',
          quantity: 50,
          desc: 'string',
          discount: 20,
          status: true,
        },
        {
          id: 13,
          pro_Id: 7,
          col_Id: 3,
          siz_Id: 3,
          price: 150000,
          importPrice: 125000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952083/TShirt/%C3%81o%20polo%20nam%20th%E1%BB%83%20thao/zb6rcw9dtc4zpoobuyrz.webp',
          quantity: 60,
          desc: 'string',
          discount: 15,
          status: true,
        },
        {
          id: 14,
          pro_Id: 7,
          col_Id: 6,
          siz_Id: 2,
          price: 120000,
          importPrice: 110000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952084/TShirt/%C3%81o%20polo%20nam%20th%E1%BB%83%20thao/lp0dfu2gedcs42ajfmse.webp',
          quantity: 50,
          desc: 'string',
          discount: 0,
          status: true,
        },
      ],
    },
    {
      id: 8,
      cat_Id: 2,
      nat_Id: 2,
      bra_Id: 2,
      sup_Id: 2,
      name: 'Áo thun J97',
      status: true,
      productVariations: [
        {
          id: 15,
          pro_Id: 8,
          col_Id: 1,
          siz_Id: 1,
          price: 999000,
          importPrice: 50000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731954121/TShirt/%C3%81o%20thun%20J97/xocbbyfs16it2cwsucyk.png',
          quantity: 97,
          desc: 'Áo thun độc quyền dành cho FC Đom Đóm - Cộng đồng fan J97.',
          discount: 10,
          status: true,
        },
        {
          id: 16,
          pro_Id: 8,
          col_Id: 1,
          siz_Id: 3,
          price: 1200000,
          importPrice: 150000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731954121/TShirt/%C3%81o%20thun%20J97/xocbbyfs16it2cwsucyk.png',
          quantity: 50,
          desc: 'string',
          discount: 10,
          status: true,
        },
        {
          id: 17,
          pro_Id: 8,
          col_Id: 2,
          siz_Id: 1,
          price: 1200000,
          importPrice: 150000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731954121/TShirt/%C3%81o%20thun%20J97/i4fwod4ki2c0fwm9y6of.png',
          quantity: 50,
          desc: 'string',
          discount: 12,
          status: true,
        },
        {
          id: 18,
          pro_Id: 8,
          col_Id: 2,
          siz_Id: 2,
          price: 1600000,
          importPrice: 150000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731954121/TShirt/%C3%81o%20thun%20J97/i4fwod4ki2c0fwm9y6of.png',
          quantity: 50,
          desc: 'string',
          discount: 12,
          status: true,
        },
        {
          id: 19,
          pro_Id: 8,
          col_Id: 2,
          siz_Id: 3,
          price: 1800000,
          importPrice: 150000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731954121/TShirt/%C3%81o%20thun%20J97/i4fwod4ki2c0fwm9y6of.png',
          quantity: 50,
          desc: 'string',
          discount: 12,
          status: true,
        },
      ],
    },
    {
      id: 9,
      cat_Id: 3,
      nat_Id: 3,
      bra_Id: 3,
      sup_Id: 3,
      name: 'Áo thun cotton lạnh',
      status: true,
      productVariations: [
        {
          id: 20,
          pro_Id: 9,
          col_Id: 2,
          siz_Id: 1,
          price: 100000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952301/TShirt/%C3%81o%20thun%20cotton%20l%E1%BA%A1nh/jb8d6rleasxempxi1rgz.webp',
          quantity: 50,
          desc: 'Áo thun với chất vải cotton lạnh mang lại cảm giác mát mẻ cho ngày hè.',
          discount: 10,
          status: true,
        },
        {
          id: 21,
          pro_Id: 9,
          col_Id: 4,
          siz_Id: 2,
          price: 120000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952301/TShirt/%C3%81o%20thun%20cotton%20l%E1%BA%A1nh/jb8d6rleasxempxi1rgz.webp',
          quantity: 50,
          desc: 'string',
          discount: 10,
          status: true,
        },
        {
          id: 22,
          pro_Id: 9,
          col_Id: 5,
          siz_Id: 3,
          price: 130000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952301/TShirt/%C3%81o%20thun%20cotton%20l%E1%BA%A1nh/jb8d6rleasxempxi1rgz.webp',
          quantity: 50,
          desc: 'string',
          discount: 10,
          status: true,
        },
        {
          id: 23,
          pro_Id: 9,
          col_Id: 2,
          siz_Id: 4,
          price: 150000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952301/TShirt/%C3%81o%20thun%20cotton%20l%E1%BA%A1nh/jb8d6rleasxempxi1rgz.webp',
          quantity: 50,
          desc: 'string',
          discount: 10,
          status: true,
        },
        {
          id: 24,
          pro_Id: 9,
          col_Id: 2,
          siz_Id: 1,
          price: 100000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952301/TShirt/%C3%81o%20thun%20cotton%20l%E1%BA%A1nh/bmbtjvmyrgkna30pmm97.webp',
          quantity: 50,
          desc: 'string',
          discount: 10,
          status: true,
        },
        {
          id: 25,
          pro_Id: 9,
          col_Id: 2,
          siz_Id: 2,
          price: 120000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952301/TShirt/%C3%81o%20thun%20cotton%20l%E1%BA%A1nh/bmbtjvmyrgkna30pmm97.webp',
          quantity: 50,
          desc: 'string',
          discount: 10,
          status: true,
        },
        {
          id: 26,
          pro_Id: 9,
          col_Id: 2,
          siz_Id: 3,
          price: 120000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952301/TShirt/%C3%81o%20thun%20cotton%20l%E1%BA%A1nh/bmbtjvmyrgkna30pmm97.webp',
          quantity: 50,
          desc: 'string',
          discount: 10,
          status: true,
        },
        {
          id: 27,
          pro_Id: 9,
          col_Id: 4,
          siz_Id: 3,
          price: 160000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952300/TShirt/%C3%81o%20thun%20cotton%20l%E1%BA%A1nh/giefwdqto7onk8mkxlki.webp',
          quantity: 3,
          desc: 'string',
          discount: 10,
          status: true,
        },
      ],
    },
    {
      id: 10,
      cat_Id: 1,
      nat_Id: 1,
      bra_Id: 1,
      sup_Id: 1,
      name: 'Áo polo Teelab',
      status: true,
      productVariations: [
        {
          id: 28,
          pro_Id: 10,
          col_Id: 2,
          siz_Id: 1,
          price: 125000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952239/TShirt/%C3%81o%20polo%20Teelab/cvpcz3k1z0y5otgu46pc.webp',
          quantity: 3,
          desc: 'Áo thun cao cấp đến từ nhà Teelab.',
          discount: 10,
          status: true,
        },
        {
          id: 29,
          pro_Id: 10,
          col_Id: 2,
          siz_Id: 2,
          price: 145000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952239/TShirt/%C3%81o%20polo%20Teelab/cvpcz3k1z0y5otgu46pc.webp',
          quantity: 30,
          desc: 'string',
          discount: 10,
          status: true,
        },
        {
          id: 30,
          pro_Id: 10,
          col_Id: 1,
          siz_Id: 3,
          price: 155000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952239/TShirt/%C3%81o%20polo%20Teelab/cvpcz3k1z0y5otgu46pc.webp',
          quantity: 10,
          desc: 'string',
          discount: 10,
          status: true,
        },
        {
          id: 31,
          pro_Id: 10,
          col_Id: 1,
          siz_Id: 4,
          price: 165000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952239/TShirt/%C3%81o%20polo%20Teelab/cvpcz3k1z0y5otgu46pc.webp',
          quantity: 20,
          desc: 'string',
          discount: 15,
          status: true,
        },
        {
          id: 32,
          pro_Id: 10,
          col_Id: 2,
          siz_Id: 1,
          price: 125000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952239/TShirt/%C3%81o%20polo%20Teelab/g58nsrw0hyotc3aha6y5.webp',
          quantity: 50,
          desc: 'string',
          discount: 10,
          status: true,
        },
        {
          id: 33,
          pro_Id: 10,
          col_Id: 2,
          siz_Id: 2,
          price: 135000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952239/TShirt/%C3%81o%20polo%20Teelab/g58nsrw0hyotc3aha6y5.webp',
          quantity: 50,
          desc: 'string',
          discount: 10,
          status: true,
        },
      ],
    },
    {
      id: 11,
      cat_Id: 1,
      nat_Id: 1,
      bra_Id: 1,
      sup_Id: 1,
      name: 'Áo thun thời trang',
      status: true,
      productVariations: [
        {
          id: 34,
          pro_Id: 11,
          col_Id: 3,
          siz_Id: 1,
          price: 120000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952257/TShirt/%C3%81o%20thun%20th%E1%BB%9Di%20trang/w8z8gmanpshdvhyvxivo.webp',
          quantity: 50,
          desc: 'Áo thun thời trang bao chất và phong cách.',
          discount: 5,
          status: true,
        },
        {
          id: 35,
          pro_Id: 11,
          col_Id: 2,
          siz_Id: 2,
          price: 140000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952257/TShirt/%C3%81o%20thun%20th%E1%BB%9Di%20trang/w8z8gmanpshdvhyvxivo.webp',
          quantity: 50,
          desc: 'Áo thun thời trang bao chất và phong cách.',
          discount: 5,
          status: true,
        },
        {
          id: 36,
          pro_Id: 11,
          col_Id: 1,
          siz_Id: 3,
          price: 160000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952257/TShirt/%C3%81o%20thun%20th%E1%BB%9Di%20trang/w8z8gmanpshdvhyvxivo.webp',
          quantity: 50,
          desc: 'Áo thun thời trang bao chất và phong cách.',
          discount: 5,
          status: true,
        },
        {
          id: 37,
          pro_Id: 11,
          col_Id: 2,
          siz_Id: 1,
          price: 120000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952257/TShirt/%C3%81o%20thun%20th%E1%BB%9Di%20trang/m0ipebnryg7fmcnuhqhg.webp',
          quantity: 60,
          desc: 'Áo thun thời trang bao chất và phong cách.',
          discount: 10,
          status: true,
        },
        {
          id: 38,
          pro_Id: 11,
          col_Id: 2,
          siz_Id: 2,
          price: 140000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952257/TShirt/%C3%81o%20thun%20th%E1%BB%9Di%20trang/m0ipebnryg7fmcnuhqhg.webp',
          quantity: 60,
          desc: 'Áo thun thời trang bao chất và phong cách.',
          discount: 10,
          status: true,
        },
        {
          id: 39,
          pro_Id: 11,
          col_Id: 3,
          siz_Id: 2,
          price: 140000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952256/TShirt/%C3%81o%20thun%20th%E1%BB%9Di%20trang/ufvoaxif8qlplrwzwz0a.webp',
          quantity: 60,
          desc: 'Áo thun thời trang bao chất và phong cách.',
          discount: 10,
          status: true,
        },
        {
          id: 40,
          pro_Id: 11,
          col_Id: 3,
          siz_Id: 3,
          price: 160000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952256/TShirt/%C3%81o%20thun%20th%E1%BB%9Di%20trang/ufvoaxif8qlplrwzwz0a.webp',
          quantity: 60,
          desc: 'Áo thun thời trang bao chất và phong cách.',
          discount: 10,
          status: true,
        },
      ],
    },
    {
      id: 12,
      cat_Id: 1,
      nat_Id: 1,
      bra_Id: 1,
      sup_Id: 1,
      name: 'Áo thun trơn',
      status: true,
      productVariations: [
        {
          id: 41,
          pro_Id: 12,
          col_Id: 4,
          siz_Id: 1,
          price: 80000,
          importPrice: 50000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952203/TShirt/%C3%81o%20thun%20tr%C6%A1n/xchtrylxw03a4j7vqezy.webp',
          quantity: 60,
          desc: 'Áo thun vải trơn không hoạ tiết.',
          discount: 0,
          status: true,
        },
        {
          id: 42,
          pro_Id: 12,
          col_Id: 3,
          siz_Id: 2,
          price: 90000,
          importPrice: 50000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952203/TShirt/%C3%81o%20thun%20tr%C6%A1n/xchtrylxw03a4j7vqezy.webp',
          quantity: 60,
          desc: 'Áo thun vải trơn không hoạ tiết.',
          discount: 0,
          status: true,
        },
        {
          id: 43,
          pro_Id: 12,
          col_Id: 2,
          siz_Id: 3,
          price: 100000,
          importPrice: 50000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952203/TShirt/%C3%81o%20thun%20tr%C6%A1n/xchtrylxw03a4j7vqezy.webp',
          quantity: 60,
          desc: 'Áo thun vải trơn không hoạ tiết.',
          discount: 0,
          status: true,
        },
        {
          id: 44,
          pro_Id: 12,
          col_Id: 2,
          siz_Id: 4,
          price: 120000,
          importPrice: 50000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952203/TShirt/%C3%81o%20thun%20tr%C6%A1n/xchtrylxw03a4j7vqezy.webp',
          quantity: 60,
          desc: 'Áo thun vải trơn không hoạ tiết.',
          discount: 0,
          status: true,
        },
        {
          id: 45,
          pro_Id: 12,
          col_Id: 2,
          siz_Id: 1,
          price: 80000,
          importPrice: 50000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952203/TShirt/%C3%81o%20thun%20tr%C6%A1n/fftvp12r8innxeumlyjc.webp',
          quantity: 60,
          desc: 'Áo thun vải trơn không hoạ tiết.',
          discount: 0,
          status: true,
        },
        {
          id: 46,
          pro_Id: 12,
          col_Id: 4,
          siz_Id: 2,
          price: 90000,
          importPrice: 50000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952203/TShirt/%C3%81o%20thun%20tr%C6%A1n/fftvp12r8innxeumlyjc.webp',
          quantity: 60,
          desc: 'Áo thun vải trơn không hoạ tiết.',
          discount: 0,
          status: true,
        },
        {
          id: 47,
          pro_Id: 12,
          col_Id: 3,
          siz_Id: 1,
          price: 80000,
          importPrice: 50000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952203/TShirt/%C3%81o%20thun%20tr%C6%A1n/pn8zkzowwzv0msv8xerc.webp',
          quantity: 60,
          desc: 'Áo thun vải trơn không hoạ tiết.',
          discount: 0,
          status: true,
        },
        {
          id: 48,
          pro_Id: 12,
          col_Id: 3,
          siz_Id: 4,
          price: 160000,
          importPrice: 50000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952203/TShirt/%C3%81o%20thun%20tr%C6%A1n/pn8zkzowwzv0msv8xerc.webp',
          quantity: 60,
          desc: 'Áo thun vải trơn không hoạ tiết.',
          discount: 0,
          status: true,
        },
      ],
    },
    {
      id: 13,
      cat_Id: 1,
      nat_Id: 1,
      bra_Id: 1,
      sup_Id: 1,
      name: 'Áo thun unisex',
      status: true,
      productVariations: [
        {
          id: 49,
          pro_Id: 13,
          col_Id: 2,
          siz_Id: 1,
          price: 120000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952187/TShirt/%C3%81o%20thun%20unisex/qm1euce0be9iauxbuim9.webp',
          quantity: 60,
          desc: 'Áo thun unisex- danh cho cả nam và nữ.',
          discount: 0,
          status: true,
        },
        {
          id: 50,
          pro_Id: 13,
          col_Id: 7,
          siz_Id: 2,
          price: 140000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952187/TShirt/%C3%81o%20thun%20unisex/qm1euce0be9iauxbuim9.webp',
          quantity: 60,
          desc: 'Áo thun unisex- danh cho cả nam và nữ.',
          discount: 0,
          status: true,
        },
        {
          id: 51,
          pro_Id: 13,
          col_Id: 3,
          siz_Id: 3,
          price: 160000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952187/TShirt/%C3%81o%20thun%20unisex/qm1euce0be9iauxbuim9.webp',
          quantity: 60,
          desc: 'Áo thun unisex- danh cho cả nam và nữ.',
          discount: 20,
          status: true,
        },
        {
          id: 52,
          pro_Id: 13,
          col_Id: 4,
          siz_Id: 1,
          price: 120000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952187/TShirt/%C3%81o%20thun%20unisex/acj7g7wl50j0q89tpyt6.webp',
          quantity: 60,
          desc: 'Áo thun unisex- danh cho cả nam và nữ.',
          discount: 10,
          status: true,
        },
        {
          id: 53,
          pro_Id: 13,
          col_Id: 2,
          siz_Id: 2,
          price: 140000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952187/TShirt/%C3%81o%20thun%20unisex/acj7g7wl50j0q89tpyt6.webp',
          quantity: 60,
          desc: 'Áo thun unisex- danh cho cả nam và nữ.',
          discount: 10,
          status: true,
        },
        {
          id: 54,
          pro_Id: 13,
          col_Id: 3,
          siz_Id: 2,
          price: 140000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952188/TShirt/%C3%81o%20thun%20unisex/a5brnueldq7vx0afqj49.webp',
          quantity: 60,
          desc: 'Áo thun unisex- danh cho cả nam và nữ.',
          discount: 10,
          status: true,
        },
        {
          id: 55,
          pro_Id: 13,
          col_Id: 3,
          siz_Id: 4,
          price: 160000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952188/TShirt/%C3%81o%20thun%20unisex/a5brnueldq7vx0afqj49.webp',
          quantity: 60,
          desc: 'Áo thun unisex- danh cho cả nam và nữ.',
          discount: 10,
          status: true,
        },
        {
          id: 56,
          pro_Id: 13,
          col_Id: 4,
          siz_Id: 1,
          price: 120000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952188/TShirt/%C3%81o%20thun%20unisex/i0s6mmysnikstf86irre.webp',
          quantity: 60,
          desc: 'Áo thun unisex- danh cho cả nam và nữ.',
          discount: 10,
          status: true,
        },
        {
          id: 57,
          pro_Id: 13,
          col_Id: 4,
          siz_Id: 2,
          price: 140000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952188/TShirt/%C3%81o%20thun%20unisex/i0s6mmysnikstf86irre.webp',
          quantity: 60,
          desc: 'Áo thun unisex- danh cho cả nam và nữ.',
          discount: 10,
          status: true,
        },
      ],
    },
    {
      id: 14,
      cat_Id: 1,
      nat_Id: 1,
      bra_Id: 1,
      sup_Id: 1,
      name: 'Áo thun phong cách',
      status: true,
      productVariations: [
        {
          id: 58,
          pro_Id: 14,
          col_Id: 2,
          siz_Id: 1,
          price: 130000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952271/TShirt/%C3%81o%20thun%20unisex%20genz/vmjuc4y2x74blmhdtyzs.webp',
          quantity: 60,
          desc: 'Áo thun phong cách MCK.',
          discount: 10,
          status: true,
        },
        {
          id: 59,
          pro_Id: 14,
          col_Id: 1,
          siz_Id: 2,
          price: 140000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952271/TShirt/%C3%81o%20thun%20unisex%20genz/vmjuc4y2x74blmhdtyzs.webp',
          quantity: 60,
          desc: 'Áo thun phong cách MCK.',
          discount: 10,
          status: true,
        },
        {
          id: 60,
          pro_Id: 14,
          col_Id: 6,
          siz_Id: 3,
          price: 150000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952271/TShirt/%C3%81o%20thun%20unisex%20genz/vmjuc4y2x74blmhdtyzs.webp',
          quantity: 60,
          desc: 'Áo thun phong cách MCK.',
          discount: 10,
          status: true,
        },
        {
          id: 61,
          pro_Id: 14,
          col_Id: 2,
          siz_Id: 1,
          price: 120000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952272/TShirt/%C3%81o%20thun%20unisex%20genz/dvho6ppjawlk4xvel7gu.webp',
          quantity: 60,
          desc: 'Áo thun phong cách MCK.',
          discount: 10,
          status: true,
        },
        {
          id: 62,
          pro_Id: 14,
          col_Id: 6,
          siz_Id: 1,
          price: 120000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731952272/TShirt/%C3%81o%20thun%20unisex%20genz/zfxqedgddd0t42wg3xze.webp',
          quantity: 60,
          desc: 'Áo thun phong cách MCK.',
          discount: 10,
          status: true,
        },
      ],
    },
    {
      id: 15,
      cat_Id: 1,
      nat_Id: 1,
      bra_Id: 1,
      sup_Id: 1,
      name: 'Áo thun Outerity',
      status: true,
      productVariations: [
        {
          id: 63,
          pro_Id: 15,
          col_Id: 1,
          siz_Id: 1,
          price: 150000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731957130/TShirt/%C3%81o%20thun%20Outerity/scl15u8j32jxbvlnjs1o.webp',
          quantity: 60,
          desc: 'Áo thun đến từ nhà Outerity.',
          discount: 10,
          status: true,
        },
        {
          id: 64,
          pro_Id: 15,
          col_Id: 2,
          siz_Id: 2,
          price: 170000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731957130/TShirt/%C3%81o%20thun%20Outerity/scl15u8j32jxbvlnjs1o.webp',
          quantity: 60,
          desc: 'Áo thun đến từ nhà Outerity.',
          discount: 10,
          status: true,
        },
        {
          id: 65,
          pro_Id: 15,
          col_Id: 2,
          siz_Id: 2,
          price: 170000,
          importPrice: 90000,
          pic: 'https://res.cloudinary.com/dt46dvdeu/image/upload/v1731957130/TShirt/%C3%81o%20thun%20Outerity/kreeoyhghmgndwzswsfa.webp',
          quantity: 60,
          desc: 'Áo thun đến từ nhà Outerity.',
          discount: 10,
          status: true,
        },
      ],
    },
  ],
  isSuccess: true,
  message: null,
};
export const ITEMS_V2: Item_v2[] = dataItemAPI.result;

/**Xu ly data item v2: end */
const dataColorAPI = {
  result: [
    {
      id: 1,
      name: 'Trắng',
      status: true,
    },
    {
      id: 2,
      name: 'Đen',
      status: true,
    },
  ],
  isSuccess: true,
  message: null,
};

const dataSizeAPI = {
  result: [
    {
      id: 1,
      name: 'S',
      desc: 'Size S, đây là size nhỏ nhất. S nghĩa là Small.',
      status: true,
    },
    {
      id: 2,
      name: 'M',
      desc: 'Size M, đây là size trung bình. M nghĩa là Medium.',
      status: true,
    },
  ],
  isSuccess: true,
  message: null,
};

const dataNationAPI = {
  result: [
    {
      id: 1,
      name: 'Việt Nam',
      status: true,
    },
    {
      id: 2,
      name: 'Trung Quốc',
      status: true,
    },
  ],
  isSuccess: true,
  message: null,
};

const dataCategoryAPI = {
  result: [
    {
      id: 1,
      name: 'Gucci',
      description: 'This is Gucci',
      status: true,
    },
    {
      id: 2,
      name: 'Fendi',
      description: 'This is Fendi',
      status: true,
    },
  ],
  isSuccess: true,
  message: null,
};

const dataBrandAPI = {
  result: [
    {
      id: 1,
      name: 'Hades',
      status: true,
    },
    {
      id: 2,
      name: 'Dirty Coins',
      status: true,
    },
  ],
  isSuccess: true,
  message: null,
};

const dataSupplierAPI = {
  result: [
    {
      supplier_ID: 1,
      supplierName: 'ABC Supplies',
      address: '123 Main St, New York, NY',
      phoneNumber: '9876543210',
      status: true,
    },
    {
      supplier_ID: 2,
      supplierName: 'Global Traders',
      address: '456 Elm St, Los Angeles, CA',
      phoneNumber: '0123456789',
      status: false,
    },
  ],
  isSuccess: true,
  message: null,
};

const dataCartAPI = {
  result: [
    {
      item_Id: 1,
      cus_Id: 1,
      price: 20000,
      quantity: 2,
    },
    {
      item_Id: 2,
      cus_Id: 1,
      price: 90000,
      quantity: 20,
    },
  ],
  isSuccess: true,
  message: null,
};
